local _, addon = ...;
local L = addon.Localization.GetDefaultLocale();
addon.L = L;

-- [[ https://legacy.curseforge.com/wow/addons/titan-panel-currency-krowis/localization ]] --
-- [[ Everything after this line is automatically generated from CurseForge and is not meant for manual edit - SOURCETOKEN - AUTOGENTOKEN ]] --

-- [[ Exported at 2025-11-28 08-39-36 ]] --
L["1 Hour"] = true
L["12 Hours"] = true
L["1k"] = true
L["1m"] = true
L["2 Hours"] = true
L["24 Hours"] = true
L["4 Hours"] = true
L["48 Hours"] = true
L["8 Hours"] = true
L["Account Total"] = true
L["Alliance:"] = true
L["Button Display"] = true
L["Character Gold"] = true
L["Character Tracking"] = true
L["Characters:"] = true
L["Combined"] = true
L["Comma"] = true
L["Currency"] = true
L["Currency Abbreviate"] = true
L["Currency by Krowi"] = true
L["Currency Group By Header"] = true
L["Currency Hide Unused"] = true
L["Currency Info"] = true
L["Currency Options"] = true
L["Current Character:"] = true
L["Current Faction Total"] = true
L["Data will be collected as you play"] = true
L["Default Tooltip"] = true
L["Earned:"] = true
L["Faction Totals:"] = true
L["Hold Ctrl: Currencies only"] = true
L["Hold Ctrl: Show currencies"] = true
L["Hold Shift: Detailed money info"] = true
L["Hold Shift: Money only"] = true
L["Hold Shift: Show currencies"] = true
L["Hold Shift: Show money"] = true
L["Horde:"] = true
L["Icon"] = true
L["Max Characters"] = true
L["Money"] = true
L["Money Abbreviate"] = true
L["Money Colored"] = true
L["Money Details"] = true
L["Money Gold Only"] = true
L["Money Label"] = true
L["Money Options"] = true
L["more characters"] = true
L["No character data available yet"] = true
L["None"] = true
L["Period"] = true
L["Realm Total"] = true
L["Release Ctrl: Show combined"] = true
L["Release Shift: Show combined"] = true
L["Release Shift: Show currencies"] = true
L["Release Shift: Show money"] = true
L["Session Duration"] = true
L["Session:"] = true
L["Show On Button"] = true
L["Space"] = true
L["Spent:"] = true
L["Text"] = true
L["Thousands Separator"] = true
L["Tooltip Options"] = true
L["Total:"] = true
L["Track All Realms"] = true
L["Track Session Gold"] = true
L["Warband Bank"] = true
L["Warband Bank:"] = true